import type { LearningLanguage } from "./language_packs";

export interface Verb {
  index: number;
  base: string;
  past: string;
  participle: string;
  translation: string;
}

const englishVerbs: Verb[] = [
  { index: 1, base: "arise", past: "arose", participle: "arisen", translation: "powstawać" },
  { index: 2, base: "awake", past: "awoke", participle: "awoken", translation: "budzić się" },
  { index: 3, base: "be", past: "was/were", participle: "been", translation: "być" },
  { index: 4, base: "bear", past: "bore", participle: "born/borne", translation: "znosić" },
  { index: 5, base: "beat", past: "beat", participle: "beaten", translation: "bić" },
  { index: 6, base: "become", past: "became", participle: "become", translation: "stawać się" },
  { index: 7, base: "begin", past: "began", participle: "begun", translation: "zaczynać" },
  { index: 8, base: "bend", past: "bent", participle: "bent", translation: "zginać" },
  { index: 9, base: "bet", past: "bet", participle: "bet", translation: "zakładać się" },
  { index: 10, base: "bind", past: "bound", participle: "bound", translation: "wiązać" },
  { index: 11, base: "bite", past: "bit", participle: "bitten", translation: "gryźć" },
  { index: 12, base: "bleed", past: "bled", participle: "bled", translation: "krwawić" },
  { index: 13, base: "blow", past: "blew", participle: "blown", translation: "wiać" },
  { index: 14, base: "break", past: "broke", participle: "broken", translation: "łamać" },
  { index: 15, base: "bring", past: "brought", participle: "brought", translation: "przynosić" },
  { index: 16, base: "build", past: "built", participle: "built", translation: "budować" },
  { index: 17, base: "burn", past: "burnt/burned", participle: "burnt/burned", translation: "palić się" },
  { index: 18, base: "buy", past: "bought", participle: "bought", translation: "kupować" },
  { index: 19, base: "catch", past: "caught", participle: "caught", translation: "łapać" },
  { index: 20, base: "choose", past: "chose", participle: "chosen", translation: "wybierać" },
  { index: 21, base: "come", past: "came", participle: "come", translation: "przychodzić" },
  { index: 22, base: "cost", past: "cost", participle: "cost", translation: "kosztować" },
  { index: 23, base: "cut", past: "cut", participle: "cut", translation: "ciąć" },
  { index: 24, base: "deal", past: "dealt", participle: "dealt", translation: "radzić sobie" },
  { index: 25, base: "dig", past: "dug", participle: "dug", translation: "kopać" },
  { index: 26, base: "do", past: "did", participle: "done", translation: "robić" },
  { index: 27, base: "draw", past: "drew", participle: "drawn", translation: "rysować" },
  { index: 28, base: "drink", past: "drank", participle: "drunk", translation: "pić" },
  { index: 29, base: "drive", past: "drove", participle: "driven", translation: "prowadzić (samochód)" },
  { index: 30, base: "eat", past: "ate", participle: "eaten", translation: "jeść" },
  { index: 31, base: "fall", past: "fell", participle: "fallen", translation: "upadać" },
  { index: 32, base: "feed", past: "fed", participle: "fed", translation: "karmić" },
  { index: 33, base: "feel", past: "felt", participle: "felt", translation: "czuć" },
  { index: 34, base: "fight", past: "fought", participle: "fought", translation: "walczyć" },
  { index: 35, base: "find", past: "found", participle: "found", translation: "znajdować" },
  { index: 36, base: "fly", past: "flew", participle: "flown", translation: "latać" },
  { index: 37, base: "forget", past: "forgot", participle: "forgotten", translation: "zapominać" },
  { index: 38, base: "forgive", past: "forgave", participle: "forgiven", translation: "wybaczać" },
  { index: 39, base: "freeze", past: "froze", participle: "frozen", translation: "zamarzać" },
  { index: 40, base: "get", past: "got", participle: "got/gotten", translation: "dostawać" },
  { index: 41, base: "give", past: "gave", participle: "given", translation: "dawać" },
  { index: 42, base: "go", past: "went", participle: "gone", translation: "iść" },
  { index: 43, base: "grow", past: "grew", participle: "grown", translation: "rosnąć" },
  { index: 44, base: "hang", past: "hung", participle: "hung", translation: "wieszać" },
  { index: 45, base: "have", past: "had", participle: "had", translation: "mieć" },
  { index: 46, base: "hear", past: "heard", participle: "heard", translation: "słyszeć" },
  { index: 47, base: "hide", past: "hid", participle: "hidden", translation: "chować" },
  { index: 48, base: "hit", past: "hit", participle: "hit", translation: "uderzać" },
  { index: 49, base: "hold", past: "held", participle: "held", translation: "trzymać" },
  { index: 50, base: "hurt", past: "hurt", participle: "hurt", translation: "ranić" },
  { index: 51, base: "keep", past: "kept", participle: "kept", translation: "trzymać" },
  { index: 52, base: "know", past: "knew", participle: "known", translation: "wiedzieć" },
  { index: 53, base: "lay", past: "laid", participle: "laid", translation: "kłaść" },
  { index: 54, base: "lead", past: "led", participle: "led", translation: "prowadzić" },
  { index: 55, base: "leave", past: "left", participle: "left", translation: "opuszczać" },
  { index: 56, base: "lend", past: "lent", participle: "lent", translation: "pożyczać" },
  { index: 57, base: "let", past: "let", participle: "let", translation: "pozwalać" },
  { index: 58, base: "lie", past: "lay", participle: "lain", translation: "leżeć" },
  { index: 59, base: "lose", past: "lost", participle: "lost", translation: "gubić" },
  { index: 60, base: "make", past: "made", participle: "made", translation: "robić, tworzyć" },
  { index: 61, base: "mean", past: "meant", participle: "meant", translation: "znaczyć" },
  { index: 62, base: "meet", past: "met", participle: "met", translation: "spotykać" },
  { index: 63, base: "pay", past: "paid", participle: "paid", translation: "płacić" },
  { index: 64, base: "put", past: "put", participle: "put", translation: "kłaść" },
  { index: 65, base: "read", past: "read", participle: "read", translation: "czytać" },
  { index: 66, base: "ride", past: "rode", participle: "ridden", translation: "jeździć" },
  { index: 67, base: "ring", past: "rang", participle: "rung", translation: "dzwonić" },
  { index: 68, base: "rise", past: "rose", participle: "risen", translation: "wschodzić" },
  { index: 69, base: "run", past: "ran", participle: "run", translation: "biegać" },
  { index: 70, base: "say", past: "said", participle: "said", translation: "mówić" },
  { index: 71, base: "see", past: "saw", participle: "seen", translation: "widzieć" },
  { index: 72, base: "sell", past: "sold", participle: "sold", translation: "sprzedawać" },
  { index: 73, base: "send", past: "sent", participle: "sent", translation: "wysyłać" },
  { index: 74, base: "set", past: "set", participle: "set", translation: "ustawiać" },
  { index: 75, base: "shake", past: "shook", participle: "shaken", translation: "trząść" },
  { index: 76, base: "shine", past: "shone", participle: "shone", translation: "świecić" },
  { index: 77, base: "shoot", past: "shot", participle: "shot", translation: "strzelać" },
  { index: 78, base: "show", past: "showed", participle: "shown", translation: "pokazywać" },
  { index: 79, base: "shut", past: "shut", participle: "shut", translation: "zamykać" },
  { index: 80, base: "sing", past: "sang", participle: "sung", translation: "śpiewać" },
  { index: 81, base: "sit", past: "sat", participle: "sat", translation: "siedzieć" },
  { index: 82, base: "sleep", past: "slept", participle: "slept", translation: "spać" },
  { index: 83, base: "speak", past: "spoke", participle: "spoken", translation: "mówić" },
  { index: 84, base: "spend", past: "spent", participle: "spent", translation: "wydawać" },
  { index: 85, base: "stand", past: "stood", participle: "stood", translation: "stać" },
  { index: 86, base: "steal", past: "stole", participle: "stolen", translation: "kraść" },
  { index: 87, base: "swim", past: "swam", participle: "swum", translation: "pływać" },
  { index: 88, base: "take", past: "took", participle: "taken", translation: "brać" },
  { index: 89, base: "teach", past: "taught", participle: "taught", translation: "uczyć (kogoś)" },
  { index: 90, base: "tell", past: "told", participle: "told", translation: "mówić (komuś)" },
  { index: 91, base: "think", past: "thought", participle: "thought", translation: "myśleć" },
  { index: 92, base: "throw", past: "threw", participle: "thrown", translation: "rzucać" },
  { index: 93, base: "understand", past: "understood", participle: "understood", translation: "rozumieć" },
  { index: 94, base: "wake", past: "woke", participle: "woken", translation: "budzić się" },
  { index: 95, base: "wear", past: "wore", participle: "worn", translation: "nosić (ubranie)" },
  { index: 96, base: "win", past: "won", participle: "won", translation: "wygrywać" },
  { index: 97, base: "write", past: "wrote", participle: "written", translation: "pisać" },
];

const germanVerbs: Verb[] = [
  { "index": 1, "base": "sein", "past": "war", "participle": "gewesen", "translation": "być" },
  { "index": 2, "base": "haben", "past": "hatte", "participle": "gehabt", "translation": "mieć" },
  { "index": 3, "base": "werden", "past": "wurde", "participle": "geworden", "translation": "stawać się" },
  { "index": 4, "base": "gehen", "past": "ging", "participle": "gegangen", "translation": "iść" },
  { "index": 5, "base": "kommen", "past": "kam", "participle": "gekommen", "translation": "przychodzić" },
  { "index": 6, "base": "sehen", "past": "sah", "participle": "gesehen", "translation": "widzieć" },
  { "index": 7, "base": "geben", "past": "gab", "participle": "gegeben", "translation": "dawać" },
  { "index": 8, "base": "nehmen", "past": "nahm", "participle": "genommen", "translation": "brać" },
  { "index": 9, "base": "finden", "past": "fand", "participle": "gefunden", "translation": "znajdować" },
  { "index": 10, "base": "denken", "past": "dachte", "participle": "gedacht", "translation": "myśleć" },
  { "index": 11, "base": "wissen", "past": "wusste", "participle": "gewusst", "translation": "wiedzieć" },
  { "index": 12, "base": "bringen", "past": "brachte", "participle": "gebracht", "translation": "przynosić" },
  { "index": 13, "base": "stehen", "past": "stand", "participle": "gestanden", "translation": "stać" },
  { "index": 14, "base": "liegen", "past": "lag", "participle": "gelegen", "translation": "leżeć" },
  { "index": 15, "base": "bleiben", "past": "blieb", "participle": "geblieben", "translation": "pozostawać" },
  { "index": 16, "base": "essen", "past": "aß", "participle": "gegessen", "translation": "jeść" },
  { "index": 17, "base": "trinken", "past": "trank", "participle": "getrunken", "translation": "pić" },
  { "index": 18, "base": "schlafen", "past": "schlief", "participle": "geschlafen", "translation": "spać" },
  { "index": 19, "base": "fahren", "past": "fuhr", "participle": "gefahren", "translation": "jechać" },
  { "index": 20, "base": "laufen", "past": "lief", "participle": "gelaufen", "translation": "biegać" },
  { "index": 21, "base": "sprechen", "past": "sprach", "participle": "gesprochen", "translation": "mówić" },
  { "index": 22, "base": "lesen", "past": "las", "participle": "gelesen", "translation": "czytać" },
  { "index": 23, "base": "schreiben", "past": "schrieb", "participle": "geschrieben", "translation": "pisać" },
  { "index": 24, "base": "beginnen", "past": "begann", "participle": "begonnen", "translation": "zaczynać" },
  { "index": 25, "base": "helfen", "past": "half", "participle": "geholfen", "translation": "pomagać" },
  { "index": 26, "base": "halten", "past": "hielt", "participle": "gehalten", "translation": "trzymać" },
  { "index": 27, "base": "lassen", "past": "ließ", "participle": "gelassen", "translation": "pozwalać" },
  { "index": 28, "base": "laufen", "past": "lief", "participle": "gelaufen", "translation": "biegać" },
  { "index": 29, "base": "sehen", "past": "sah", "participle": "gesehen", "translation": "widzieć" },
  { "index": 30, "base": "sitzen", "past": "saß", "participle": "gesessen", "translation": "siedzieć" },
  { "index": 31, "base": "ziehen", "past": "zog", "participle": "gezogen", "translation": "ciągnąć" },
  { "index": 32, "base": "schließen", "past": "schloss", "participle": "geschlossen", "translation": "zamykać" },
  { "index": 33, "base": "schneiden", "past": "schnitt", "participle": "geschnitten", "translation": "ciąć" },
  { "index": 34, "base": "singen", "past": "sang", "participle": "gesungen", "translation": "śpiewać" },
  { "index": 35, "base": "beginnen", "past": "begann", "participle": "begonnen", "translation": "rozpoczynać" },
  { "index": 36, "base": "gewinnen", "past": "gewann", "participle": "gewonnen", "translation": "wygrywać" },
  { "index": 37, "base": "verlieren", "past": "verlor", "participle": "verloren", "translation": "przegrywać" },
  { "index": 38, "base": "scheinen", "past": "schien", "participle": "geschienen", "translation": "świecić / wydawać się" },
  { "index": 39, "base": "bringen", "past": "brachte", "participle": "gebracht", "translation": "przynosić" },
  { "index": 40, "base": "denken", "past": "dachte", "participle": "gedacht", "translation": "myśleć" },
  { "index": 41, "base": "kennen", "past": "kannte", "participle": "gekannt", "translation": "znać" },
  { "index": 42, "base": "nennen", "past": "nannte", "participle": "genannt", "translation": "nazywać" },
  { "index": 43, "base": "rennen", "past": "rannte", "participle": "gerannt", "translation": "biec" },
  { "index": 44, "base": "tun", "past": "tat", "participle": "getan", "translation": "robić" },
  { "index": 45, "base": "stehen", "past": "stand", "participle": "gestanden", "translation": "stać" },
  { "index": 46, "base": "liegen", "past": "lag", "participle": "gelegen", "translation": "leżeć" },
  { "index": 47, "base": "fallen", "past": "fiel", "participle": "gefallen", "translation": "upadać" },
  { "index": 48, "base": "beginnen", "past": "begann", "participle": "begonnen", "translation": "zaczynać" },
  { "index": 49, "base": "vergessen", "past": "vergaß", "participle": "vergessen", "translation": "zapominać" },
  { "index": 50, "base": "treffen", "past": "traf", "participle": "getroffen", "translation": "spotykać" },
  { "index": 51, "base": "rufen", "past": "rief", "participle": "gerufen", "translation": "wołać" },
  { "index": 52, "base": "schwimmen", "past": "schwamm", "participle": "geschwommen", "translation": "pływać" },
  { "index": 53, "base": "stehen", "past": "stand", "participle": "gestanden", "translation": "stać" },
  { "index": 54, "base": "tragen", "past": "trug", "participle": "getragen", "translation": "nosić" },
  { "index": 55, "base": "waschen", "past": "wusch", "participle": "gewaschen", "translation": "myć" },
  { "index": 56, "base": "vergessen", "past": "vergaß", "participle": "vergessen", "translation": "zapominać" },
  { "index": 57, "base": "ziehen", "past": "zog", "participle": "gezogen", "translation": "ciągnąć" },
  { "index": 58, "base": "bitten", "past": "bat", "participle": "gebeten", "translation": "prosić" },
  { "index": 59, "base": "beginnen", "past": "begann", "participle": "begonnen", "translation": "zaczynać" },
  { "index": 60, "base": "empfehlen", "past": "empfahl", "participle": "empfohlen", "translation": "polecać" },
  { "index": 61, "base": "fliegen", "past": "flog", "participle": "geflogen", "translation": "latać" },
  { "index": 62, "base": "brechen", "past": "brach", "participle": "gebrochen", "translation": "łamać" },
  { "index": 63, "base": "sterben", "past": "starb", "participle": "gestorben", "translation": "umierać" },
  { "index": 64, "base": "vergessen", "past": "vergaß", "participle": "vergessen", "translation": "zapominać" },
  { "index": 65, "base": "schreiben", "past": "schrieb", "participle": "geschrieben", "translation": "pisać" },
  { "index": 66, "base": "singen", "past": "sang", "participle": "gesungen", "translation": "śpiewać" },
  { "index": 67, "base": "springen", "past": "sprang", "participle": "gesprungen", "translation": "skakać" },
  { "index": 68, "base": "bieten", "past": "bot", "participle": "geboten", "translation": "oferować" },
  { "index": 69, "base": "fallen", "past": "fiel", "participle": "gefallen", "translation": "spadać" },
  { "index": 70, "base": "laufen", "past": "lief", "participle": "gelaufen", "translation": "biec" },
  { "index": 71, "base": "finden", "past": "fand", "participle": "gefunden", "translation": "znajdować" },
  { "index": 72, "base": "vergessen", "past": "vergaß", "participle": "vergessen", "translation": "zapominać" },
  { "index": 73, "base": "stehen", "past": "stand", "participle": "gestanden", "translation": "stać" },
  { "index": 74, "base": "lesen", "past": "las", "participle": "gelesen", "translation": "czytać" },
  { "index": 75, "base": "sehen", "past": "sah", "participle": "gesehen", "translation": "widzieć" },
  { "index": 76, "base": "fallen", "past": "fiel", "participle": "gefallen", "translation": "upadać" },
  { "index": 77, "base": "treiben", "past": "trieb", "participle": "getrieben", "translation": "prowadzić, uprawiać (sport)" },
  { "index": 78, "base": "steigen", "past": "stieg", "participle": "gestiegen", "translation": "wspinać się" },
  { "index": 79, "base": "scheinen", "past": "schien", "participle": "geschienen", "translation": "świecić, wydawać się" },
  { "index": 80, "base": "tragen", "past": "trug", "participle": "getragen", "translation": "nosić" }
];


const spanishVerbs: Verb[] = [
  { "index": 1, "base": "ser", "past": "fui", "participle": "sido", "translation": "być" },
  { "index": 2, "base": "ir", "past": "fui", "participle": "ido", "translation": "iść" },
  { "index": 3, "base": "tener", "past": "tuve", "participle": "tenido", "translation": "mieć" },
  { "index": 4, "base": "hacer", "past": "hice", "participle": "hecho", "translation": "robić" },
  { "index": 5, "base": "decir", "past": "dije", "participle": "dicho", "translation": "mówić" },
  { "index": 6, "base": "poder", "past": "pude", "participle": "podido", "translation": "móc" },
  { "index": 7, "base": "poner", "past": "puse", "participle": "puesto", "translation": "kłaść" },
  { "index": 8, "base": "venir", "past": "vine", "participle": "venido", "translation": "przychodzić" },
  { "index": 9, "base": "ver", "past": "vi", "participle": "visto", "translation": "widzieć" },
  { "index": 10, "base": "dar", "past": "di", "participle": "dado", "translation": "dawać" },
  { "index": 11, "base": "querer", "past": "quise", "participle": "querido", "translation": "chcieć" },
  { "index": 12, "base": "saber", "past": "supe", "participle": "sabido", "translation": "wiedzieć" },
  { "index": 13, "base": "traer", "past": "traje", "participle": "traído", "translation": "przynosić" },
  { "index": 14, "base": "andar", "past": "anduve", "participle": "andado", "translation": "chodzić" },
  { "index": 15, "base": "estar", "past": "estuve", "participle": "estado", "translation": "być (tymczasowo)" },
  { "index": 16, "base": "traducir", "past": "traduje", "participle": "traducido", "translation": "tłumaczyć" },
  { "index": 17, "base": "conducir", "past": "conduje", "participle": "conducido", "translation": "prowadzić" },
  { "index": 18, "base": "producir", "past": "produje", "participle": "producido", "translation": "produkować" },
  { "index": 19, "base": "haber", "past": "hube", "participle": "habido", "translation": "mieć (czasownik pomocniczy)" },
  { "index": 20, "base": "oír", "past": "oí", "participle": "oído", "translation": "słyszeć" },
  { "index": 21, "base": "caer", "past": "caí", "participle": "caído", "translation": "upadać" },
  { "index": 22, "base": "creer", "past": "creí", "participle": "creído", "translation": "wierzyć" },
  { "index": 23, "base": "leer", "past": "leí", "participle": "leído", "translation": "czytać" },
  { "index": 24, "base": "dormir", "past": "dormí", "participle": "dormido", "translation": "spać" },
  { "index": 25, "base": "sentir", "past": "sentí", "participle": "sentido", "translation": "czuć" },
  { "index": 26, "base": "pedir", "past": "pedí", "participle": "pedido", "translation": "prosić" },
  { "index": 27, "base": "servir", "past": "serví", "participle": "servido", "translation": "służyć" },
  { "index": 28, "base": "reír", "past": "reí", "participle": "reído", "translation": "śmiać się" },
  { "index": 29, "base": "sonreír", "past": "sonreí", "participle": "sonreído", "translation": "uśmiechać się" },
  { "index": 30, "base": "seguir", "past": "seguí", "participle": "seguido", "translation": "podążać" },
  { "index": 31, "base": "conseguir", "past": "conseguí", "participle": "conseguido", "translation": "osiągać" },
  { "index": 32, "base": "morir", "past": "morí", "participle": "muerto", "translation": "umierać" },
  { "index": 33, "base": "abrir", "past": "abrí", "participle": "abierto", "translation": "otwierać" },
  { "index": 34, "base": "cubrir", "past": "cubrí", "participle": "cubierto", "translation": "przykrywać" },
  { "index": 35, "base": "descubrir", "past": "descubrí", "participle": "descubierto", "translation": "odkrywać" },
  { "index": 36, "base": "volver", "past": "volví", "participle": "vuelto", "translation": "wracać" },
  { "index": 37, "base": "resolver", "past": "resolví", "participle": "resuelto", "translation": "rozwiązywać" },
  { "index": 38, "base": "romper", "past": "rompí", "participle": "roto", "translation": "łamać" },
  { "index": 39, "base": "poner", "past": "puse", "participle": "puesto", "translation": "kłaść" },
  { "index": 40, "base": "imprimir", "past": "imprimí", "participle": "impreso", "translation": "drukować" },
  { "index": 41, "base": "freír", "past": "freí", "participle": "frito", "translation": "smażyć" },
  { "index": 42, "base": "escribir", "past": "escribí", "participle": "escrito", "translation": "pisać" },
  { "index": 43, "base": "decidir", "past": "decidí", "participle": "decidido", "translation": "decydować" },
  { "index": 44, "base": "proveer", "past": "proveí", "participle": "provisto", "translation": "zaopatrywać" },
  { "index": 45, "base": "venir", "past": "vine", "participle": "venido", "translation": "przychodzić" },
  { "index": 46, "base": "mantener", "past": "mantuve", "participle": "mantenido", "translation": "utrzymywać" },
  { "index": 47, "base": "obtener", "past": "obtuve", "participle": "obtenido", "translation": "uzyskać" },
  { "index": 48, "base": "detener", "past": "detuve", "participle": "detenido", "translation": "zatrzymywać" },
  { "index": 49, "base": "construir", "past": "construí", "participle": "construido", "translation": "budować" },
  { "index": 50, "base": "destruir", "past": "destruí", "participle": "destruido", "translation": "niszczyć" },
  { "index": 51, "base": "incluir", "past": "incluí", "participle": "incluido", "translation": "zawierać" },
  { "index": 52, "base": "huir", "past": "huí", "participle": "huido", "translation": "uciekać" },
  { "index": 53, "base": "jugar", "past": "jugué", "participle": "jugado", "translation": "grać" },
  { "index": 54, "base": "buscar", "past": "busqué", "participle": "buscado", "translation": "szukać" },
  { "index": 55, "base": "pagar", "past": "pagué", "participle": "pagado", "translation": "płacić" },
  { "index": 56, "base": "empezar", "past": "empecé", "participle": "empezado", "translation": "zaczynać" },
  { "index": 57, "base": "almorzar", "past": "almorcé", "participle": "almorzado", "translation": "jeść obiad" },
  { "index": 58, "base": "tocar", "past": "toqué", "participle": "tocado", "translation": "dotykać / grać (na instrumencie)" },
  { "index": 59, "base": "sacar", "past": "saqué", "participle": "sacado", "translation": "wyciągać" },
  { "index": 60, "base": "llegar", "past": "llegué", "participle": "llegado", "translation": "przybywać" },
  { "index": 61, "base": "averiguar", "past": "averigüé", "participle": "averiguado", "translation": "sprawdzać, dowiadywać się" },
  { "index": 62, "base": "mentir", "past": "mentí", "participle": "mentido", "translation": "kłamać" },
  { "index": 63, "base": "preferir", "past": "preferí", "participle": "preferido", "translation": "woleć" },
  { "index": 64, "base": "cerrar", "past": "cerré", "participle": "cerrado", "translation": "zamykać" },
  { "index": 65, "base": "pensar", "past": "pensé", "participle": "pensado", "translation": "myśleć" },
  { "index": 66, "base": "entender", "past": "entendí", "participle": "entendido", "translation": "rozumieć" },
  { "index": 67, "base": "perder", "past": "perdí", "participle": "perdido", "translation": "tracić" },
  { "index": 68, "base": "contar", "past": "conté", "participle": "contado", "translation": "liczyć / opowiadać" },
  { "index": 69, "base": "recordar", "past": "recordé", "participle": "recordado", "translation": "pamiętać" },
  { "index": 70, "base": "mostrar", "past": "mostré", "participle": "mostrado", "translation": "pokazywać" },
  { "index": 71, "base": "mover", "past": "moví", "participle": "movido", "translation": "ruszać" },
  { "index": 72, "base": "costar", "past": "costé", "participle": "costado", "translation": "kosztować" },
  { "index": 73, "base": "valer", "past": "valí", "participle": "valido", "translation": "być wartym" },
  { "index": 74, "base": "caber", "past": "cupe", "participle": "cabido", "translation": "mieścić się" },
  { "index": 75, "base": "reducir", "past": "reduje", "participle": "reducido", "translation": "redukować" },
  { "index": 76, "base": "introducir", "past": "introduje", "participle": "introducido", "translation": "wprowadzać" },
  { "index": 77, "base": "producir", "past": "produje", "participle": "producido", "translation": "produkować" },
  { "index": 78, "base": "decir", "past": "dije", "participle": "dicho", "translation": "mówić" },
  { "index": 79, "base": "venir", "past": "vine", "participle": "venido", "translation": "przychodzić" },
  { "index": 80, "base": "tener", "past": "tuve", "participle": "tenido", "translation": "mieć" }
]


export const VERB_SETS: Record<LearningLanguage, Verb[]> = {
  en: englishVerbs,
  de: germanVerbs,
  es: spanishVerbs,
};
