export interface Verb {
  index: number;
  base: string;
  past: string;
  participle: string;
  translation: string;
}

export const verbs: Verb[] = [

  { index: 1, base: "arise", past: "arose", participle: "arisen", translation: "powstawać" },
  { index: 2, base: "awake", past: "awoke", participle: "awoken", translation: "budzić się" },
  { index: 3, base: "be", past: "was/were", participle: "been", translation: "być" },
  { index: 4, base: "bear", past: "bore", participle: "born/borne", translation: "znosić" },
  { index: 5, base: "beat", past: "beat", participle: "beaten", translation: "bić" },
  { index: 6, base: "become", past: "became", participle: "become", translation: "stawać się" },
  { index: 7, base: "begin", past: "began", participle: "begun", translation: "zaczynać" },
  { index: 8, base: "bend", past: "bent", participle: "bent", translation: "zginać" },
  { index: 9, base: "bet", past: "bet", participle: "bet", translation: "zakładać się" },
  { index: 10, base: "bind", past: "bound", participle: "bound", translation: "wiązać" },
  { index: 11, base: "bite", past: "bit", participle: "bitten", translation: "gryźć" },
  { index: 12, base: "bleed", past: "bled", participle: "bled", translation: "krwawić" },
  { index: 13, base: "blow", past: "blew", participle: "blown", translation: "wiać" },
  { index: 14, base: "break", past: "broke", participle: "broken", translation: "łamać" },
  { index: 15, base: "bring", past: "brought", participle: "brought", translation: "przynosić" },
  { index: 16, base: "build", past: "built", participle: "built", translation: "budować" },
  { index: 17, base: "burn", past: "burnt/burned", participle: "burnt/burned", translation: "palić się" },
  { index: 18, base: "buy", past: "bought", participle: "bought", translation: "kupować" },
  { index: 19, base: "catch", past: "caught", participle: "caught", translation: "łapać" },
  { index: 20, base: "choose", past: "chose", participle: "chosen", translation: "wybierać" },
  { index: 21, base: "come", past: "came", participle: "come", translation: "przychodzić" },
  { index: 22, base: "cost", past: "cost", participle: "cost", translation: "kosztować" },
  { index: 23, base: "cut", past: "cut", participle: "cut", translation: "ciąć" },
  { index: 24, base: "deal", past: "dealt", participle: "dealt", translation: "radzić sobie" },
  { index: 25, base: "dig", past: "dug", participle: "dug", translation: "kopać" },
  { index: 26, base: "do", past: "did", participle: "done", translation: "robić" },
  { index: 27, base: "draw", past: "drew", participle: "drawn", translation: "rysować" },
  { index: 28, base: "drink", past: "drank", participle: "drunk", translation: "pić" },
  { index: 29, base: "drive", past: "drove", participle: "driven", translation: "prowadzić (samochód)" },
  { index: 30, base: "eat", past: "ate", participle: "eaten", translation: "jeść" },
  { index: 31, base: "fall", past: "fell", participle: "fallen", translation: "upadać" },
  { index: 32, base: "feed", past: "fed", participle: "fed", translation: "karmić" },
  { index: 33, base: "feel", past: "felt", participle: "felt", translation: "czuć" },
  { index: 34, base: "fight", past: "fought", participle: "fought", translation: "walczyć" },
  { index: 35, base: "find", past: "found", participle: "found", translation: "znajdować" },
  { index: 36, base: "fly", past: "flew", participle: "flown", translation: "latać" },
  { index: 37, base: "forget", past: "forgot", participle: "forgotten", translation: "zapominać" },
  { index: 38, base: "forgive", past: "forgave", participle: "forgiven", translation: "wybaczać" },
  { index: 39, base: "freeze", past: "froze", participle: "frozen", translation: "zamarzać" },
  { index: 40, base: "get", past: "got", participle: "got/gotten", translation: "dostawać" },
  { index: 41, base: "give", past: "gave", participle: "given", translation: "dawać" },
  { index: 42, base: "go", past: "went", participle: "gone", translation: "iść" },
  { index: 43, base: "grow", past: "grew", participle: "grown", translation: "rosnąć" },
  { index: 44, base: "hang", past: "hung", participle: "hung", translation: "wieszać" },
  { index: 45, base: "have", past: "had", participle: "had", translation: "mieć" },
  { index: 46, base: "hear", past: "heard", participle: "heard", translation: "słyszeć" },
  { index: 47, base: "hide", past: "hid", participle: "hidden", translation: "chować" },
  { index: 48, base: "hit", past: "hit", participle: "hit", translation: "uderzać" },
  { index: 49, base: "hold", past: "held", participle: "held", translation: "trzymać" },
  { index: 50, base: "hurt", past: "hurt", participle: "hurt", translation: "ranić" },
  { index: 51, base: "keep", past: "kept", participle: "kept", translation: "trzymać" },
  { index: 52, base: "know", past: "knew", participle: "known", translation: "wiedzieć" },
  { index: 53, base: "lay", past: "laid", participle: "laid", translation: "kłaść" },
  { index: 54, base: "lead", past: "led", participle: "led", translation: "prowadzić" },
  { index: 55, base: "leave", past: "left", participle: "left", translation: "opuszczać" },
  { index: 56, base: "lend", past: "lent", participle: "lent", translation: "pożyczać" },
  { index: 57, base: "let", past: "let", participle: "let", translation: "pozwalać" },
  { index: 58, base: "lie", past: "lay", participle: "lain", translation: "leżeć" },
  { index: 59, base: "lose", past: "lost", participle: "lost", translation: "gubić" },
  { index: 60, base: "make", past: "made", participle: "made", translation: "robić, tworzyć" },
  { index: 61, base: "mean", past: "meant", participle: "meant", translation: "znaczyć" },
  { index: 62, base: "meet", past: "met", participle: "met", translation: "spotykać" },
  { index: 63, base: "pay", past: "paid", participle: "paid", translation: "płacić" },
  { index: 64, base: "put", past: "put", participle: "put", translation: "kłaść" },
  { index: 65, base: "read", past: "read", participle: "read", translation: "czytać" },
  { index: 66, base: "ride", past: "rode", participle: "ridden", translation: "jeździć" },
  { index: 67, base: "ring", past: "rang", participle: "rung", translation: "dzwonić" },
  { index: 68, base: "rise", past: "rose", participle: "risen", translation: "wschodzić" },
  { index: 69, base: "run", past: "ran", participle: "run", translation: "biegać" },
  { index: 70, base: "say", past: "said", participle: "said", translation: "mówić" },
  { index: 71, base: "see", past: "saw", participle: "seen", translation: "widzieć" },
  { index: 72, base: "sell", past: "sold", participle: "sold", translation: "sprzedawać" },
  { index: 73, base: "send", past: "sent", participle: "sent", translation: "wysyłać" },
  { index: 74, base: "set", past: "set", participle: "set", translation: "ustawiać" },
  { index: 75, base: "shake", past: "shook", participle: "shaken", translation: "trząść" },
  { index: 76, base: "shine", past: "shone", participle: "shone", translation: "świecić" },
  { index: 77, base: "shoot", past: "shot", participle: "shot", translation: "strzelać" },
  { index: 78, base: "show", past: "showed", participle: "shown", translation: "pokazywać" },
  { index: 79, base: "shut", past: "shut", participle: "shut", translation: "zamykać" },
  { index: 80, base: "sing", past: "sang", participle: "sung", translation: "śpiewać" },
  { index: 81, base: "sit", past: "sat", participle: "sat", translation: "siedzieć" },
  { index: 82, base: "sleep", past: "slept", participle: "slept", translation: "spać" },
  { index: 83, base: "speak", past: "spoke", participle: "spoken", translation: "mówić" },
  { index: 84, base: "spend", past: "spent", participle: "spent", translation: "wydawać" },
  { index: 85, base: "stand", past: "stood", participle: "stood", translation: "stać" },
  { index: 86, base: "steal", past: "stole", participle: "stolen", translation: "kraść" },
  { index: 87, base: "swim", past: "swam", participle: "swum", translation: "pływać" },
  { index: 88, base: "take", past: "took", participle: "taken", translation: "brać" },
  { index: 89, base: "teach", past: "taught", participle: "taught", translation: "uczyć (kogoś)" },
  { index: 90, base: "tell", past: "told", participle: "told", translation: "mówić (komuś)" },
  { index: 91, base: "think", past: "thought", participle: "thought", translation: "myśleć" },
  { index: 92, base: "throw", past: "threw", participle: "thrown", translation: "rzucać" },
  { index: 93, base: "understand", past: "understood", participle: "understood", translation: "rozumieć" },
  { index: 94, base: "wake", past: "woke", participle: "woken", translation: "budzić się" },
  { index: 95, base: "wear", past: "wore", participle: "worn", translation: "nosić (ubranie)" },
  { index: 96, base: "win", past: "won", participle: "won", translation: "wygrywać" },
  { index: 97, base: "write", past: "wrote", participle: "written", translation: "pisać" }
];